/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * MetreMate API Documentation
 */
import { useQuery } from "@tanstack/vue-query"
import type { QueryFunction, QueryKey, UseQueryOptions, UseQueryReturnType } from "@tanstack/vue-query"

import { computed, unref } from "vue"
import type { MaybeRef } from "vue"

import { customFetch } from "../utils/customFetch"
type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export type getApiGetUserResponse200 = {
  data: void
  status: 200
}

export type getApiGetUserResponseSuccess = getApiGetUserResponse200 & {
  headers: Headers
}
export type getApiGetUserResponse = getApiGetUserResponseSuccess

export const getGetApiGetUserUrl = () => {
  return `/api/get.user`
}

export const getApiGetUser = async (options?: RequestInit): Promise<getApiGetUserResponse> => {
  return customFetch<getApiGetUserResponse>(getGetApiGetUserUrl(), {
    ...options,
    method: "GET"
  })
}

export const getGetApiGetUserQueryKey = () => {
  return ["api", "get.user"] as const
}

export const getGetApiGetUserQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiGetUser>>,
  TError = unknown
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getApiGetUser>>, TError, TData>
  request?: SecondParameter<typeof customFetch>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getGetApiGetUserQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiGetUser>>> = ({ signal }) =>
    getApiGetUser({ signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiGetUser>>,
    TError,
    TData
  >
}

export type GetApiGetUserQueryResult = NonNullable<Awaited<ReturnType<typeof getApiGetUser>>>
export type GetApiGetUserQueryError = unknown

export function useGetApiGetUser<TData = Awaited<ReturnType<typeof getApiGetUser>>, TError = unknown>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getApiGetUser>>, TError, TData>
  request?: SecondParameter<typeof customFetch>
}): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetApiGetUserQueryOptions(options)

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & { queryKey: QueryKey }

  query.queryKey = unref(queryOptions).queryKey as QueryKey

  return query
}

export type getNuxtErrorResponse200 = {
  data: void
  status: 200
}

export type getNuxtErrorResponseSuccess = getNuxtErrorResponse200 & {
  headers: Headers
}
export type getNuxtErrorResponse = getNuxtErrorResponseSuccess

export const getGetNuxtErrorUrl = () => {
  return `/__nuxt_error`
}

export const getNuxtError = async (options?: RequestInit): Promise<getNuxtErrorResponse> => {
  return customFetch<getNuxtErrorResponse>(getGetNuxtErrorUrl(), {
    ...options,
    method: "GET"
  })
}

export const getGetNuxtErrorQueryKey = () => {
  return ["__nuxt_error"] as const
}

export const getGetNuxtErrorQueryOptions = <
  TData = Awaited<ReturnType<typeof getNuxtError>>,
  TError = unknown
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getNuxtError>>, TError, TData>
  request?: SecondParameter<typeof customFetch>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getGetNuxtErrorQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getNuxtError>>> = ({ signal }) =>
    getNuxtError({ signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getNuxtError>>,
    TError,
    TData
  >
}

export type GetNuxtErrorQueryResult = NonNullable<Awaited<ReturnType<typeof getNuxtError>>>
export type GetNuxtErrorQueryError = unknown

export function useGetNuxtError<TData = Awaited<ReturnType<typeof getNuxtError>>, TError = unknown>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getNuxtError>>, TError, TData>
  request?: SecondParameter<typeof customFetch>
}): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetNuxtErrorQueryOptions(options)

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & { queryKey: QueryKey }

  query.queryKey = unref(queryOptions).queryKey as QueryKey

  return query
}

export type getNuxtIslandParam1Response200 = {
  data: void
  status: 200
}

export type getNuxtIslandParam1ResponseSuccess = getNuxtIslandParam1Response200 & {
  headers: Headers
}
export type getNuxtIslandParam1Response = getNuxtIslandParam1ResponseSuccess

export const getGetNuxtIslandParam1Url = (param1: string) => {
  return `/__nuxt_island/${param1}`
}

export const getNuxtIslandParam1 = async (
  param1: string,
  options?: RequestInit
): Promise<getNuxtIslandParam1Response> => {
  return customFetch<getNuxtIslandParam1Response>(getGetNuxtIslandParam1Url(param1), {
    ...options,
    method: "GET"
  })
}

export const getGetNuxtIslandParam1QueryKey = (param1?: MaybeRef<string>) => {
  return ["__nuxt_island", param1] as const
}

export const getGetNuxtIslandParam1QueryOptions = <
  TData = Awaited<ReturnType<typeof getNuxtIslandParam1>>,
  TError = unknown
>(
  param1: MaybeRef<string>,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getNuxtIslandParam1>>, TError, TData>
    request?: SecondParameter<typeof customFetch>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getGetNuxtIslandParam1QueryKey(param1)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getNuxtIslandParam1>>> = ({ signal }) =>
    getNuxtIslandParam1(unref(param1), { signal, ...requestOptions })

  return { queryKey, queryFn, enabled: computed(() => !!unref(param1)), ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getNuxtIslandParam1>>,
    TError,
    TData
  >
}

export type GetNuxtIslandParam1QueryResult = NonNullable<Awaited<ReturnType<typeof getNuxtIslandParam1>>>
export type GetNuxtIslandParam1QueryError = unknown

export function useGetNuxtIslandParam1<TData = Awaited<ReturnType<typeof getNuxtIslandParam1>>, TError = unknown>(
  param1: MaybeRef<string>,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getNuxtIslandParam1>>, TError, TData>
    request?: SecondParameter<typeof customFetch>
  }
): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetNuxtIslandParam1QueryOptions(param1, options)

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & { queryKey: QueryKey }

  query.queryKey = unref(queryOptions).queryKey as QueryKey

  return query
}

export type getApiNuxtIconCollectionResponse200 = {
  data: void
  status: 200
}

export type getApiNuxtIconCollectionResponseSuccess = getApiNuxtIconCollectionResponse200 & {
  headers: Headers
}
export type getApiNuxtIconCollectionResponse = getApiNuxtIconCollectionResponseSuccess

export const getGetApiNuxtIconCollectionUrl = (collection: string) => {
  return `/api/_nuxt_icon/${collection}`
}

export const getApiNuxtIconCollection = async (
  collection: string,
  options?: RequestInit
): Promise<getApiNuxtIconCollectionResponse> => {
  return customFetch<getApiNuxtIconCollectionResponse>(getGetApiNuxtIconCollectionUrl(collection), {
    ...options,
    method: "GET"
  })
}

export const getGetApiNuxtIconCollectionQueryKey = (collection?: MaybeRef<string>) => {
  return ["api", "_nuxt_icon", collection] as const
}

export const getGetApiNuxtIconCollectionQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiNuxtIconCollection>>,
  TError = unknown
>(
  collection: MaybeRef<string>,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getApiNuxtIconCollection>>, TError, TData>
    request?: SecondParameter<typeof customFetch>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getGetApiNuxtIconCollectionQueryKey(collection)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiNuxtIconCollection>>> = ({ signal }) =>
    getApiNuxtIconCollection(unref(collection), { signal, ...requestOptions })

  return { queryKey, queryFn, enabled: computed(() => !!unref(collection)), ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiNuxtIconCollection>>,
    TError,
    TData
  >
}

export type GetApiNuxtIconCollectionQueryResult = NonNullable<Awaited<ReturnType<typeof getApiNuxtIconCollection>>>
export type GetApiNuxtIconCollectionQueryError = unknown

export function useGetApiNuxtIconCollection<
  TData = Awaited<ReturnType<typeof getApiNuxtIconCollection>>,
  TError = unknown
>(
  collection: MaybeRef<string>,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getApiNuxtIconCollection>>, TError, TData>
    request?: SecondParameter<typeof customFetch>
  }
): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetApiNuxtIconCollectionQueryOptions(collection, options)

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & { queryKey: QueryKey }

  query.queryKey = unref(queryOptions).queryKey as QueryKey

  return query
}

export type getDocsOpenapiJsonResponse200 = {
  data: void
  status: 200
}

export type getDocsOpenapiJsonResponseSuccess = getDocsOpenapiJsonResponse200 & {
  headers: Headers
}
export type getDocsOpenapiJsonResponse = getDocsOpenapiJsonResponseSuccess

export const getGetDocsOpenapiJsonUrl = () => {
  return `/_docs/openapi.json`
}

export const getDocsOpenapiJson = async (options?: RequestInit): Promise<getDocsOpenapiJsonResponse> => {
  return customFetch<getDocsOpenapiJsonResponse>(getGetDocsOpenapiJsonUrl(), {
    ...options,
    method: "GET"
  })
}

export const getGetDocsOpenapiJsonQueryKey = () => {
  return ["_docs", "openapi.json"] as const
}

export const getGetDocsOpenapiJsonQueryOptions = <
  TData = Awaited<ReturnType<typeof getDocsOpenapiJson>>,
  TError = unknown
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getDocsOpenapiJson>>, TError, TData>
  request?: SecondParameter<typeof customFetch>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getGetDocsOpenapiJsonQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDocsOpenapiJson>>> = ({ signal }) =>
    getDocsOpenapiJson({ signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getDocsOpenapiJson>>,
    TError,
    TData
  >
}

export type GetDocsOpenapiJsonQueryResult = NonNullable<Awaited<ReturnType<typeof getDocsOpenapiJson>>>
export type GetDocsOpenapiJsonQueryError = unknown

export function useGetDocsOpenapiJson<
  TData = Awaited<ReturnType<typeof getDocsOpenapiJson>>,
  TError = unknown
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getDocsOpenapiJson>>, TError, TData>
  request?: SecondParameter<typeof customFetch>
}): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetDocsOpenapiJsonQueryOptions(options)

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & { queryKey: QueryKey }

  query.queryKey = unref(queryOptions).queryKey as QueryKey

  return query
}

export type getDocsResponse200 = {
  data: void
  status: 200
}

export type getDocsResponseSuccess = getDocsResponse200 & {
  headers: Headers
}
export type getDocsResponse = getDocsResponseSuccess

export const getGetDocsUrl = () => {
  return `/docs`
}

export const getDocs = async (options?: RequestInit): Promise<getDocsResponse> => {
  return customFetch<getDocsResponse>(getGetDocsUrl(), {
    ...options,
    method: "GET"
  })
}

export const getGetDocsQueryKey = () => {
  return ["docs"] as const
}

export const getGetDocsQueryOptions = <TData = Awaited<ReturnType<typeof getDocs>>, TError = unknown>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getDocs>>, TError, TData>
  request?: SecondParameter<typeof customFetch>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getGetDocsQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDocs>>> = ({ signal }) =>
    getDocs({ signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof getDocs>>, TError, TData>
}

export type GetDocsQueryResult = NonNullable<Awaited<ReturnType<typeof getDocs>>>
export type GetDocsQueryError = unknown

export function useGetDocs<TData = Awaited<ReturnType<typeof getDocs>>, TError = unknown>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getDocs>>, TError, TData>
  request?: SecondParameter<typeof customFetch>
}): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetDocsQueryOptions(options)

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & { queryKey: QueryKey }

  query.queryKey = unref(queryOptions).queryKey as QueryKey

  return query
}

export type getSwaggerResponse200 = {
  data: void
  status: 200
}

export type getSwaggerResponseSuccess = getSwaggerResponse200 & {
  headers: Headers
}
export type getSwaggerResponse = getSwaggerResponseSuccess

export const getGetSwaggerUrl = () => {
  return `/_swagger`
}

export const getSwagger = async (options?: RequestInit): Promise<getSwaggerResponse> => {
  return customFetch<getSwaggerResponse>(getGetSwaggerUrl(), {
    ...options,
    method: "GET"
  })
}

export const getGetSwaggerQueryKey = () => {
  return ["_swagger"] as const
}

export const getGetSwaggerQueryOptions = <TData = Awaited<ReturnType<typeof getSwagger>>, TError = unknown>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getSwagger>>, TError, TData>
  request?: SecondParameter<typeof customFetch>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getGetSwaggerQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSwagger>>> = ({ signal }) =>
    getSwagger({ signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSwagger>>,
    TError,
    TData
  >
}

export type GetSwaggerQueryResult = NonNullable<Awaited<ReturnType<typeof getSwagger>>>
export type GetSwaggerQueryError = unknown

export function useGetSwagger<TData = Awaited<ReturnType<typeof getSwagger>>, TError = unknown>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getSwagger>>, TError, TData>
  request?: SecondParameter<typeof customFetch>
}): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetSwaggerQueryOptions(options)

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & { queryKey: QueryKey }

  query.queryKey = unref(queryOptions).queryKey as QueryKey

  return query
}
